package io.github.gcdd1993.jpa.autogen.entity.repository;

import io.github.gcdd1993.jpa.autogen.entity.Role;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * generated by jpa-autogen
 *
 * @author gaochen
 * Created On 2019/06/20.
 */
public interface RoleRepository extends JpaRepository<Role, Long> {
}