package ${packageName};

import lombok.Data;
<#list imports as import>
import ${import};
</#list>

/**
 * form for ${entity.className} generated by jpa-codegen
 * ${comments}
 *
 * @author ${author}
 * Created On ${date}.
 */
@Data
public class ${className} {

    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * TODO 字段描述
     */
    private ${f.className} ${f.name};

    </#list>
    </#if>
}