package ${package_name};

import ${entity_full_name};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;

/**
 * auto generated by <a href=""></a>
 * @author ${author}
 * Created On ${date}.
 */
public interface ${entity_simple_name}${repository_suffix} extends JpaRepository<${entity_simple_name}, ${entity_id}>, QueryDslPredicateExecutor<${entity_simple_name}> {
}