package io.github.gcdd1993.repository;

import io.github.gcdd1993.entity.Role;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * generated by jpa-autogen
 * @author gaochen
 * Created On 2019/06/19.
 */
public interface RoleRepository extends JpaRepository<Role, Long> {
}