package io.github.gcdd1993.repository;

import io.github.gcdd1993.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * generated by jpa-autogen
 * @author gaochen
 * Created On 2019/06/19.
 */
public interface UserRepository extends JpaRepository<User, Long> {
}